services:
  client:
    image: asia-south1-docker.pkg.dev/lloyds-hack-grp-35/finadvisor-ai/frontend:latest
    build:
      dockerfile: Dockerfile
      context: ./FrontEnd
    networks:
      - ts-network
  server:
    image: asia-south1-docker.pkg.dev/lloyds-hack-grp-35/finadvisor-ai/backend:latest
    build:
      dockerfile: Dockerfile
      context: ./BackEnd
    networks:
      - ts-network

networks:
  ts-network:
    driver: bridge
    