services:
  client:
    image: asia-south1-docker.pkg.dev/lloyds-hack-grp-35/finadvisor-ai/frontend:latest
    ports:
      - 80:3000
    networks:
      - ts-network
    environment:
      - API_URL=http://localhost:81/
  server:
    image: asia-south1-docker.pkg.dev/lloyds-hack-grp-35/finadvisor-ai/backend:latest
    ports:
      - 81:5400
    networks:
      - ts-network

networks:
  ts-network:
    driver: bridge
    